from enum import StrEnum


class ReviewState(StrEnum):
    RECEIVED = "RECEIVED"
    TRIAGE = "TRIAGE"
    COLLECT_CONTEXT = "COLLECT_CONTEXT"
    INVESTIGATE = "INVESTIGATE"
    EVALUATE = "EVALUATE"
    VALIDATE_FINDINGS = "VALIDATE_FINDINGS"
    COMMENT_PLAN = "COMMENT_PLAN"
    PUBLISH = "PUBLISH"
    DONE = "DONE"
    SKIPPED = "SKIPPED"
    NEEDS_HUMAN = "NEEDS_HUMAN"
    ERROR = "ERROR"
